var pirate01Convo = [
	{s: "pirate", t: "Ahoy there, stranger."},
	{s: "pirate", t: "New in town?"},
	{label: "initialOptions", answers: [
		{option: "My name's Guybrush Threepwood.  I'm new in town.", next: "myNamesGuybrush"},
		{option: "Are you a pirate? Can I be on your crew?", next: "areYouAPirate"},
		{option: "Who's in charge here?", next: "whosInChargeHere"},
		{option: "Nice talking to you.", next: "niceTalkingToYou"},
	]},
	{label: "myNamesGuybrush", s: "guybrush", t: "My name's Guybrush Threepwood.  I'm new in town."},
	{s: "pirate", t: "Guybrush Threepwood?"},
	{s: "pirate", t: "Ha ha ha!!!"},
	{s: "pirate", t: "That's the stupidest name I've ever heard!"},
	{label: "thatsTheStupidestName", answers:[
		{option: "I don't know... I kind of like 'Guybrush.'", next: "iDontKnowIKindOfLikeGuybrush"},
		{option: "Well, what's YOUR name?", next: "wellWhatsYourName"},
		{option: "Yeah, it is pretty dumb, isn't it?", next: "yeahItIsPrettyDumb"},
		{option: "I'm insulted.  Goodbye.", next: "imInsulted"},
	]},
	{label: "iDontKnowIKindOfLikeGuybrush", s: "guybrush", t: "I don't know... I kind of like 'Guybrush'"},
	{s: "pirate", t: "But it's not even a name!"},
	{label: "butItsNotEvenAName", answers:[
		{option: "Well, what's YOUR name?", next: "wellWhatsYourName"},
		{option: "Yeah, it is pretty dumb, isn't it?", next: "yeahItIsPrettyDumb"},
		{option: "I'm insulted.  Goodbye.", next: "imInsulted"},
	]},
	{label: "wellWhatsYourName", s: "guybrush", t: "Well, what's YOUR name?"},
	{s: "pirate", t: "My name is Mancomb Seepgood."},
	{s: "pirate", t: "So what brings you to M&ecirc,l&eacute,e Island anyway?"},
	{label: "whatBringsYouToMeleeIsland", answers:[
		{option: "I want to be a pirate!", next: "iWantToBeAPirate"},
		{option: "I've come seeking my fortune.", next: "iveComeSeekingMyFortune"},
		{option: "I really don't know", next: "iReallyDontKnow"},
		{option: "None of your business. Goodbye.", next: "noneOfYourBusiness"},
	]},
	{label: "yeahItIsPrettyDumb", s: "guybrush", t: "Yeah, it is pretty dumb, isn't it?"},
	{s: "pirate", t: "That's okay."},
	{s: "pirate", t: "Mine is Mancomb Seepgood."},
	{s: "pirate", t: "So what brings you to M&ecirc,l&eacute,e Island anyway?", next: "whatBringsYouToMeleeIsland"},
	{label: "imInsulted", s: "guybrush", t: "I'm insulted.  Goodbye."},
	{s: "pirate", t: "Sorry to see you go away mad."},
	{s: "pirate", t: "Don't be a stranger.", next: "EXIT"},
	{label: "iWantToBeAPirate", s: "guybrush", t: "I want to be a pirate!"},
	{s: "pirate", t: "Oh, really?"},
	{s: "pirate", t: "You should go talk to the important-looking pirates in the next room."},
	{s: "pirate", t: "They're pretty much in charge around here."},
	{s: "pirate", t: "They can tell you where to go and what to do."},
	{label: "wantPirateChoices", answers: [
		{option: "Where can I find the Governor?", next: "whereCanIFindGovernor"},
		{option: "Nice talking to you.", next: "niceTalkingToYou"},
	]},
	{label: "whereCanIFindGovernor", s: "guybrush", t: "Where can I find the Governor?"},
	{s: "pirate", t: "Governor Marley?"},
	{s: "pirate", t: "Her mansion is on the other side of town."},
	{s: "pirate", t: "But pirates aren't as welcome around her place as they used to be."},
	{label: "whereFindGovernorChoices", answers: [
		{option: "Why Not?", next: "whyNot"},
		{option: "I'm welcome everywhere I go.", next: "welcomeEverywhere"},
		{option: "I think I'll go there right now. Bye.", next: "goRightNow"},
	]},
	{label: "whyNot", s: "guybrush", t: "Why not?"},
	{s: "pirate", t: "Well, the last time she had a pirate over for dinner, he fell in love with her."},
	{s: "pirate", t: "It's made things rather uncomfortable for everybody."},
	{label: "whyNotOptions", answers:[
		{option: "How's that?", next: "howsThat"},
		{option: "Who is this pirate?", next: "whoIsThisPirate"},
		{option: "That's too bad.  Well, see you later.", next: "thatsTooBad"},
	]},
	{label: "howsThat", s: "guybrush", t: "How's that?"},
	{s: "pirate", t: "Well, there's a whole big story about what happened next..."},
	{s: "pirate", t: "But I don't believe a word of it."},
	{s: "pirate", t: "Estevan over there at the other table might tell you about it."},
	{s: "pirate", t: "He takes the whole thing seriously."},
	{s: "pirate", t: "VERY seriously."},
	{s: "pirate", t: "Uh-oh, it looks like my grog is going flat, so  you'll have to excuse me."},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island.", next: "EXIT"},
	{label: "whoIsThisPirate", s: "guybrush", t: "Who is this pirate?"},
	{s: "pirate", t: "It was none other than the fearsome pirate LeChuck"},
	{s: "pirate", t: "Well, there's a whole big story about what happened next..."},
	{s: "pirate", t: "But I don't believe a word of it."},
	{s: "pirate", t: "Estevan over there at the other table might tell you about it."},
	{s: "pirate", t: "He takes the whole thing seriously."},
	{s: "pirate", t: "VERY seriously."},
	{s: "pirate", t: "Uh-oh, it looks like my grog is going flat, so  you'll have to excuse me."},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island.", next: "EXIT"},
	{label: "thatsTooBad", s: "guybrush", t: "That's too bad.  Well, see you later"},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island."}, 
	{s: "pirate", t: "My grog is going flat, so you'll have to excuse me.", next: "EXIT"},
	{label: "welcomeEverywhere", s: "guybrush", t: "I'm welcome everywhere I go."},
	{s: "pirate", t: "Whatever you say."},
	{s: "pirate", t: "Just watch out for those guard dogs!"},
	{s: "pirate", t: "Uh-oh, it looks like my grog is going flat, so  you'll have to excuse me."},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island.", next: "EXIT"},
	{label: "goRightNow", s: "guybrush", t: "I think I'll go there right now. Bye."},
	{s: "pirate", t: "Okay, but watch out for those guard dogs!"},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island."}, 
	{s: "pirate", t: "My grog is going flat, so you'll have to excuse me.", next: "EXIT"},
	{label: "iveComeSeekingMyFortune", s: "guybrush", t: "I've come seeking my fortune."},
	{s: "pirate", t: "Oh, you have, have you?"},
	{s: "pirate", t: "You should go talk to the important-looking pirates in the next room."},
	{s: "pirate", t: "They're pretty much in charge around here."},
	{s: "pirate", t: "They can tell you where to go and what to do.", next: "wantPirateChoices"},
	{label: "iReallyDontKnow", s: "guybrush", t: "I really don't know."},
	{s: "pirate", t: "Well, it sure wasn't for the sunshine."},
	{s: "pirate", t: "I think you need some guidance."},
	{s: "pirate", t: "You should go talk to the important-looking pirates in the next room."},
	{s: "pirate", t: "They're pretty much in charge around here."},
	{s: "pirate", t: "They can tell you where to go and what to do.", next: "wantPirateChoices"},
	{label: "noneOfYourBusiness", s: "guybrush", t: "None of your business.  Goodbye."},
	{s: "pirate", t: "Well, excuse me Mr. Secretive.", next: "EXIT"},
	{label: "areYouAPirate", s: "guybrush", t: "Are you a pirate? Can I be on your crew?"},
	{s: "pirate", t: "Well, I am a pirate."},
	{s: "pirate", t: "But, alas, I'm not a captain."},
	{s: "pirate", t: "You should go talk to the important-looking pirates in the next room."},
	{s: "pirate", t: "They're pretty much in charge around here."},
	{s: "pirate", t: "They can tell you where to go and what to do.", next: "initialOptions"},
	{label: "whosInChargeHere", s: "guybrush", t: "Who's in charge here?"},
	{s: "pirate", t: "Well, this island has a governor..."},
	{s: "pirate", t: "...but we pirates have our own leaders."},
	{label: "inChargeOptions", answers: [
		{option: "I want to talk to the leaders of the pirates.", next: "talkPirateLeaders"},
		{option: "Where can I find the Governor of the island?", next: "whereFindGovernor"},
		{option: "That's nice.  Goodbye.", next: "thatsNice"},
	]},
	{label: "talkPirateLeaders", s: "guybrush", t: "I want to talk to the leaders of the pirates."},
	{s: "pirate", t: "You should go talk to the important-looking pirates in the next room."},
	{s: "pirate", t: "They're pretty much in charge around here."},
	{s: "pirate", t: "They can tell you where to go and what to do.", next: "initialOptions", remove: "whosInChargeHere"},
	{label: "whereFindGovernor", s: "guybrush", t: "Where can I find the Governor of the island?"},
	{s: "pirate", t: "Governor Marley?"},
	{s: "pirate", t: "Her mansion is on the other side of town."},
	{s: "pirate", t: "But pirates aren't as welcome around her place as they used to be.", next: "whereFindGovernorChoices"},
	{label: "thatsNice", s: "guybrush", t: "That's nice.  Goodbye."},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island.", next: "EXIT"},
	{label: "niceTalkingToYou", s: "guybrush", t: "Nice talking to you."},
	{s: "pirate", t: "Nice talking to you."},
	{s: "pirate", t: "Have fun on M&ecirc,l&eacute,e Island.", next: "EXIT"}
];
